// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2018.3
// Copyright (C) 1986-2018 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "blobsCount.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic blobsCount::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic blobsCount::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<6> blobsCount::ap_ST_fsm_state1 = "1";
const sc_lv<6> blobsCount::ap_ST_fsm_pp0_stage0 = "10";
const sc_lv<6> blobsCount::ap_ST_fsm_pp0_stage1 = "100";
const sc_lv<6> blobsCount::ap_ST_fsm_state10 = "1000";
const sc_lv<6> blobsCount::ap_ST_fsm_state11 = "10000";
const sc_lv<6> blobsCount::ap_ST_fsm_state12 = "100000";
const bool blobsCount::ap_const_boolean_1 = true;
const sc_lv<32> blobsCount::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> blobsCount::ap_const_lv32_1 = "1";
const bool blobsCount::ap_const_boolean_0 = false;
const sc_lv<1> blobsCount::ap_const_lv1_0 = "0";
const sc_lv<32> blobsCount::ap_const_lv32_2 = "10";
const sc_lv<1> blobsCount::ap_const_lv1_1 = "1";
const sc_lv<32> blobsCount::ap_const_lv32_3 = "11";
const sc_lv<32> blobsCount::ap_const_lv32_4 = "100";
const sc_lv<15> blobsCount::ap_const_lv15_0 = "000000000000000";
const sc_lv<8> blobsCount::ap_const_lv8_0 = "00000000";
const sc_lv<8> blobsCount::ap_const_lv8_FF = "11111111";
const sc_lv<8> blobsCount::ap_const_lv8_1 = "1";
const sc_lv<15> blobsCount::ap_const_lv15_7DDC = "111110111011100";
const sc_lv<15> blobsCount::ap_const_lv15_1 = "1";
const sc_lv<8> blobsCount::ap_const_lv8_B3 = "10110011";
const sc_lv<8> blobsCount::ap_const_lv8_2 = "10";
const sc_lv<15> blobsCount::ap_const_lv15_B4 = "10110100";
const sc_lv<15> blobsCount::ap_const_lv15_B5 = "10110101";
const sc_lv<15> blobsCount::ap_const_lv15_7E90 = "111111010010000";
const sc_lv<2> blobsCount::ap_const_lv2_2 = "10";
const sc_lv<2> blobsCount::ap_const_lv2_1 = "1";
const sc_lv<3> blobsCount::ap_const_lv3_1 = "1";
const sc_lv<3> blobsCount::ap_const_lv3_3 = "11";
const sc_lv<32> blobsCount::ap_const_lv32_1F = "11111";
const sc_lv<32> blobsCount::ap_const_lv32_5 = "101";
const sc_lv<31> blobsCount::ap_const_lv31_0 = "0000000000000000000000000000000";

blobsCount::blobsCount(sc_module_name name) : sc_module(name), mVcdFile(0) {

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state10);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state11);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_state2_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state3_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state4_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state5_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state6_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state7_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state8_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state9_pp0_stage1_iter3);

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state2);
    sensitive << ( exitcond_flatten_fu_183_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_ap_phi_mux_i_phi_fu_114_p4);
    sensitive << ( i_reg_110 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten_reg_454 );
    sensitive << ( i_cast5_mid2_reg_475 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_indvar_flatten_phi_fu_103_p4);
    sensitive << ( indvar_flatten_reg_99 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten_reg_454 );
    sensitive << ( indvar_flatten_next_reg_458 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_phi_mux_j_phi_fu_138_p4);
    sensitive << ( j_reg_134 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( exitcond_flatten_reg_454 );
    sensitive << ( j_4_reg_494 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state12 );

    SC_METHOD(thread_ap_return);
    sensitive << ( tmp_26_reg_597 );
    sensitive << ( ap_CS_fsm_state12 );
    sensitive << ( p_neg_t_fu_432_p2 );
    sensitive << ( p_lshr_f_cast_fu_438_p1 );

    SC_METHOD(thread_exitcond5_fu_195_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond_flatten_fu_183_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_j_phi_fu_138_p4 );

    SC_METHOD(thread_exitcond_flatten_fu_183_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_103_p4 );

    SC_METHOD(thread_external_fu_329_p2);
    sensitive << ( external_1_reg_122 );

    SC_METHOD(thread_foreground_clean_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( tmp_30_fu_257_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_36_fu_285_p1 );

    SC_METHOD(thread_foreground_clean_address1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_33_fu_261_p1 );
    sensitive << ( tmp_40_fu_294_p1 );

    SC_METHOD(thread_foreground_clean_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_foreground_clean_ce1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter1 );

    SC_METHOD(thread_grp_fu_165_p2);
    sensitive << ( reg_157 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( exitcond_flatten_reg_454_pp0_iter2_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_grp_fu_171_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( exitcond_flatten_reg_454_pp0_iter2_reg );
    sensitive << ( reg_161 );
    sensitive << ( tmp_39_reg_541 );
    sensitive << ( ap_enable_reg_pp0_iter3 );

    SC_METHOD(thread_i_17_cast_mid2_cast_fu_243_p1);
    sensitive << ( i_17_cast_mid2_fu_238_p3 );

    SC_METHOD(thread_i_17_cast_mid2_fu_238_p3);
    sensitive << ( i_17_reg_448 );
    sensitive << ( exitcond5_reg_463 );
    sensitive << ( i_17_mid1_reg_481 );

    SC_METHOD(thread_i_17_fu_177_p2);
    sensitive << ( ap_phi_mux_i_phi_fu_114_p4 );

    SC_METHOD(thread_i_17_mid1_fu_215_p2);
    sensitive << ( i_reg_110 );

    SC_METHOD(thread_i_cast5_mid2_cast_fu_235_p1);
    sensitive << ( i_cast5_mid2_reg_475 );

    SC_METHOD(thread_i_cast5_mid2_fu_209_p3);
    sensitive << ( i_reg_110 );
    sensitive << ( i_17_reg_448 );
    sensitive << ( exitcond5_reg_463 );

    SC_METHOD(thread_indvar_flatten_next_fu_189_p2);
    sensitive << ( ap_phi_mux_indvar_flatten_phi_fu_103_p4 );

    SC_METHOD(thread_internal_2_fu_383_p3);
    sensitive << ( internal_1_reg_145 );
    sensitive << ( internal_reg_577 );
    sensitive << ( tmp_43_fu_377_p2 );

    SC_METHOD(thread_internal_fu_335_p2);
    sensitive << ( internal_1_reg_145 );

    SC_METHOD(thread_j_4_fu_230_p2);
    sensitive << ( j_mid2_reg_469 );

    SC_METHOD(thread_j_mid2_fu_201_p3);
    sensitive << ( exitcond5_fu_195_p2 );
    sensitive << ( ap_phi_mux_j_phi_fu_138_p4 );

    SC_METHOD(thread_p_cast_fu_298_p1);
    sensitive << ( tmp_31_reg_551 );

    SC_METHOD(thread_p_external_1_fu_370_p3);
    sensitive << ( external_1_reg_122 );
    sensitive << ( external_reg_572 );
    sensitive << ( tmp_42_fu_364_p2 );

    SC_METHOD(thread_p_lshr_cast_fu_429_p1);
    sensitive << ( tmp_24_reg_607 );

    SC_METHOD(thread_p_lshr_f_cast_fu_438_p1);
    sensitive << ( tmp_25_reg_602 );

    SC_METHOD(thread_p_neg_fu_414_p2);
    sensitive << ( tmp_reg_592 );

    SC_METHOD(thread_p_neg_t_fu_432_p2);
    sensitive << ( p_lshr_cast_fu_429_p1 );

    SC_METHOD(thread_p_px_1_30_fu_350_p3);
    sensitive << ( tmp_41_reg_567 );
    sensitive << ( p_px_1_cast_fu_341_p1 );
    sensitive << ( px_4_fu_344_p2 );

    SC_METHOD(thread_p_px_1_cast_fu_341_p1);
    sensitive << ( p_px_1_reg_562 );

    SC_METHOD(thread_p_px_1_fu_321_p3);
    sensitive << ( grp_fu_165_p2 );
    sensitive << ( px_1_fu_308_p3 );
    sensitive << ( px_2_fu_315_p2 );

    SC_METHOD(thread_px_1_fu_308_p3);
    sensitive << ( tmp_34_reg_557 );
    sensitive << ( px_fu_301_p3 );
    sensitive << ( p_cast_fu_298_p1 );

    SC_METHOD(thread_px_2_fu_315_p2);
    sensitive << ( px_1_fu_308_p3 );

    SC_METHOD(thread_px_3_fu_357_p3);
    sensitive << ( tmp_39_reg_541_pp0_iter3_reg );
    sensitive << ( p_px_1_cast_fu_341_p1 );
    sensitive << ( p_px_1_30_fu_350_p3 );

    SC_METHOD(thread_px_4_fu_344_p2);
    sensitive << ( p_px_1_cast_fu_341_p1 );

    SC_METHOD(thread_px_fu_301_p3);
    sensitive << ( tmp_31_reg_551 );

    SC_METHOD(thread_tmp1_fu_265_p2);
    sensitive << ( tmp_28_reg_486 );

    SC_METHOD(thread_tmp2_fu_275_p2);
    sensitive << ( tmp_28_reg_486 );

    SC_METHOD(thread_tmp_28_fu_224_p0);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( tmp_28_fu_224_p00 );

    SC_METHOD(thread_tmp_28_fu_224_p00);
    sensitive << ( j_mid2_reg_469 );

    SC_METHOD(thread_tmp_28_fu_224_p2);
    sensitive << ( tmp_28_fu_224_p0 );

    SC_METHOD(thread_tmp_29_fu_247_p2);
    sensitive << ( tmp_28_reg_486 );
    sensitive << ( i_cast5_mid2_cast_fu_235_p1 );

    SC_METHOD(thread_tmp_30_fu_257_p1);
    sensitive << ( tmp_29_reg_505 );

    SC_METHOD(thread_tmp_32_fu_252_p2);
    sensitive << ( tmp_28_reg_486 );
    sensitive << ( i_17_cast_mid2_cast_fu_243_p1 );

    SC_METHOD(thread_tmp_33_fu_261_p1);
    sensitive << ( tmp_32_reg_510 );

    SC_METHOD(thread_tmp_35_fu_270_p2);
    sensitive << ( i_cast5_mid2_cast_reg_499 );
    sensitive << ( tmp1_fu_265_p2 );

    SC_METHOD(thread_tmp_36_fu_285_p1);
    sensitive << ( tmp_35_reg_525 );

    SC_METHOD(thread_tmp_38_fu_280_p2);
    sensitive << ( i_cast5_mid2_cast_reg_499 );
    sensitive << ( tmp2_fu_275_p2 );

    SC_METHOD(thread_tmp_39_fu_289_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( exitcond_flatten_reg_454_pp0_iter1_reg );
    sensitive << ( tmp_38_reg_530 );

    SC_METHOD(thread_tmp_40_fu_294_p1);
    sensitive << ( tmp_38_reg_530 );

    SC_METHOD(thread_tmp_42_fu_364_p2);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( exitcond_flatten_reg_454_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( px_3_fu_357_p3 );

    SC_METHOD(thread_tmp_43_fu_377_p2);
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( exitcond_flatten_reg_454_pp0_iter3_reg );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( px_3_fu_357_p3 );

    SC_METHOD(thread_tmp_fu_390_p2);
    sensitive << ( external_1_reg_122 );
    sensitive << ( internal_1_reg_145 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( exitcond_flatten_fu_183_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage1_subdone );

    ap_CS_fsm = "000001";
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "blobsCount_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, foreground_clean_address0, "(port)foreground_clean_address0");
    sc_trace(mVcdFile, foreground_clean_ce0, "(port)foreground_clean_ce0");
    sc_trace(mVcdFile, foreground_clean_q0, "(port)foreground_clean_q0");
    sc_trace(mVcdFile, foreground_clean_address1, "(port)foreground_clean_address1");
    sc_trace(mVcdFile, foreground_clean_ce1, "(port)foreground_clean_ce1");
    sc_trace(mVcdFile, foreground_clean_q1, "(port)foreground_clean_q1");
    sc_trace(mVcdFile, ap_return, "(port)ap_return");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, indvar_flatten_reg_99, "indvar_flatten_reg_99");
    sc_trace(mVcdFile, i_reg_110, "i_reg_110");
    sc_trace(mVcdFile, external_1_reg_122, "external_1_reg_122");
    sc_trace(mVcdFile, j_reg_134, "j_reg_134");
    sc_trace(mVcdFile, internal_1_reg_145, "internal_1_reg_145");
    sc_trace(mVcdFile, reg_157, "reg_157");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, ap_block_state2_pp0_stage0_iter0, "ap_block_state2_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state4_pp0_stage0_iter1, "ap_block_state4_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state6_pp0_stage0_iter2, "ap_block_state6_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state8_pp0_stage0_iter3, "ap_block_state8_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_454, "exitcond_flatten_reg_454");
    sc_trace(mVcdFile, exitcond_flatten_reg_454_pp0_iter1_reg, "exitcond_flatten_reg_454_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state3_pp0_stage1_iter0, "ap_block_state3_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state5_pp0_stage1_iter1, "ap_block_state5_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state7_pp0_stage1_iter2, "ap_block_state7_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state9_pp0_stage1_iter3, "ap_block_state9_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, exitcond_flatten_reg_454_pp0_iter2_reg, "exitcond_flatten_reg_454_pp0_iter2_reg");
    sc_trace(mVcdFile, reg_161, "reg_161");
    sc_trace(mVcdFile, i_17_fu_177_p2, "i_17_fu_177_p2");
    sc_trace(mVcdFile, i_17_reg_448, "i_17_reg_448");
    sc_trace(mVcdFile, exitcond_flatten_fu_183_p2, "exitcond_flatten_fu_183_p2");
    sc_trace(mVcdFile, exitcond_flatten_reg_454_pp0_iter3_reg, "exitcond_flatten_reg_454_pp0_iter3_reg");
    sc_trace(mVcdFile, indvar_flatten_next_fu_189_p2, "indvar_flatten_next_fu_189_p2");
    sc_trace(mVcdFile, indvar_flatten_next_reg_458, "indvar_flatten_next_reg_458");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, exitcond5_fu_195_p2, "exitcond5_fu_195_p2");
    sc_trace(mVcdFile, exitcond5_reg_463, "exitcond5_reg_463");
    sc_trace(mVcdFile, j_mid2_fu_201_p3, "j_mid2_fu_201_p3");
    sc_trace(mVcdFile, j_mid2_reg_469, "j_mid2_reg_469");
    sc_trace(mVcdFile, i_cast5_mid2_fu_209_p3, "i_cast5_mid2_fu_209_p3");
    sc_trace(mVcdFile, i_cast5_mid2_reg_475, "i_cast5_mid2_reg_475");
    sc_trace(mVcdFile, i_17_mid1_fu_215_p2, "i_17_mid1_fu_215_p2");
    sc_trace(mVcdFile, i_17_mid1_reg_481, "i_17_mid1_reg_481");
    sc_trace(mVcdFile, tmp_28_fu_224_p2, "tmp_28_fu_224_p2");
    sc_trace(mVcdFile, tmp_28_reg_486, "tmp_28_reg_486");
    sc_trace(mVcdFile, j_4_fu_230_p2, "j_4_fu_230_p2");
    sc_trace(mVcdFile, j_4_reg_494, "j_4_reg_494");
    sc_trace(mVcdFile, i_cast5_mid2_cast_fu_235_p1, "i_cast5_mid2_cast_fu_235_p1");
    sc_trace(mVcdFile, i_cast5_mid2_cast_reg_499, "i_cast5_mid2_cast_reg_499");
    sc_trace(mVcdFile, tmp_29_fu_247_p2, "tmp_29_fu_247_p2");
    sc_trace(mVcdFile, tmp_29_reg_505, "tmp_29_reg_505");
    sc_trace(mVcdFile, tmp_32_fu_252_p2, "tmp_32_fu_252_p2");
    sc_trace(mVcdFile, tmp_32_reg_510, "tmp_32_reg_510");
    sc_trace(mVcdFile, tmp_35_fu_270_p2, "tmp_35_fu_270_p2");
    sc_trace(mVcdFile, tmp_35_reg_525, "tmp_35_reg_525");
    sc_trace(mVcdFile, tmp_38_fu_280_p2, "tmp_38_fu_280_p2");
    sc_trace(mVcdFile, tmp_38_reg_530, "tmp_38_reg_530");
    sc_trace(mVcdFile, tmp_39_fu_289_p2, "tmp_39_fu_289_p2");
    sc_trace(mVcdFile, tmp_39_reg_541, "tmp_39_reg_541");
    sc_trace(mVcdFile, tmp_39_reg_541_pp0_iter3_reg, "tmp_39_reg_541_pp0_iter3_reg");
    sc_trace(mVcdFile, grp_fu_165_p2, "grp_fu_165_p2");
    sc_trace(mVcdFile, tmp_31_reg_551, "tmp_31_reg_551");
    sc_trace(mVcdFile, grp_fu_171_p2, "grp_fu_171_p2");
    sc_trace(mVcdFile, tmp_34_reg_557, "tmp_34_reg_557");
    sc_trace(mVcdFile, p_px_1_fu_321_p3, "p_px_1_fu_321_p3");
    sc_trace(mVcdFile, p_px_1_reg_562, "p_px_1_reg_562");
    sc_trace(mVcdFile, tmp_41_reg_567, "tmp_41_reg_567");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, external_fu_329_p2, "external_fu_329_p2");
    sc_trace(mVcdFile, external_reg_572, "external_reg_572");
    sc_trace(mVcdFile, internal_fu_335_p2, "internal_fu_335_p2");
    sc_trace(mVcdFile, internal_reg_577, "internal_reg_577");
    sc_trace(mVcdFile, p_external_1_fu_370_p3, "p_external_1_fu_370_p3");
    sc_trace(mVcdFile, internal_2_fu_383_p3, "internal_2_fu_383_p3");
    sc_trace(mVcdFile, tmp_fu_390_p2, "tmp_fu_390_p2");
    sc_trace(mVcdFile, tmp_reg_592, "tmp_reg_592");
    sc_trace(mVcdFile, ap_CS_fsm_state10, "ap_CS_fsm_state10");
    sc_trace(mVcdFile, tmp_26_reg_597, "tmp_26_reg_597");
    sc_trace(mVcdFile, tmp_25_reg_602, "tmp_25_reg_602");
    sc_trace(mVcdFile, tmp_24_reg_607, "tmp_24_reg_607");
    sc_trace(mVcdFile, ap_CS_fsm_state11, "ap_CS_fsm_state11");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state2, "ap_condition_pp0_exit_iter0_state2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_phi_mux_indvar_flatten_phi_fu_103_p4, "ap_phi_mux_indvar_flatten_phi_fu_103_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, ap_phi_mux_i_phi_fu_114_p4, "ap_phi_mux_i_phi_fu_114_p4");
    sc_trace(mVcdFile, ap_phi_mux_j_phi_fu_138_p4, "ap_phi_mux_j_phi_fu_138_p4");
    sc_trace(mVcdFile, tmp_30_fu_257_p1, "tmp_30_fu_257_p1");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, tmp_33_fu_261_p1, "tmp_33_fu_261_p1");
    sc_trace(mVcdFile, tmp_36_fu_285_p1, "tmp_36_fu_285_p1");
    sc_trace(mVcdFile, tmp_40_fu_294_p1, "tmp_40_fu_294_p1");
    sc_trace(mVcdFile, tmp_28_fu_224_p0, "tmp_28_fu_224_p0");
    sc_trace(mVcdFile, i_17_cast_mid2_fu_238_p3, "i_17_cast_mid2_fu_238_p3");
    sc_trace(mVcdFile, i_17_cast_mid2_cast_fu_243_p1, "i_17_cast_mid2_cast_fu_243_p1");
    sc_trace(mVcdFile, tmp1_fu_265_p2, "tmp1_fu_265_p2");
    sc_trace(mVcdFile, tmp2_fu_275_p2, "tmp2_fu_275_p2");
    sc_trace(mVcdFile, px_fu_301_p3, "px_fu_301_p3");
    sc_trace(mVcdFile, p_cast_fu_298_p1, "p_cast_fu_298_p1");
    sc_trace(mVcdFile, px_1_fu_308_p3, "px_1_fu_308_p3");
    sc_trace(mVcdFile, px_2_fu_315_p2, "px_2_fu_315_p2");
    sc_trace(mVcdFile, p_px_1_cast_fu_341_p1, "p_px_1_cast_fu_341_p1");
    sc_trace(mVcdFile, px_4_fu_344_p2, "px_4_fu_344_p2");
    sc_trace(mVcdFile, p_px_1_30_fu_350_p3, "p_px_1_30_fu_350_p3");
    sc_trace(mVcdFile, px_3_fu_357_p3, "px_3_fu_357_p3");
    sc_trace(mVcdFile, tmp_42_fu_364_p2, "tmp_42_fu_364_p2");
    sc_trace(mVcdFile, tmp_43_fu_377_p2, "tmp_43_fu_377_p2");
    sc_trace(mVcdFile, p_neg_fu_414_p2, "p_neg_fu_414_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, p_lshr_cast_fu_429_p1, "p_lshr_cast_fu_429_p1");
    sc_trace(mVcdFile, p_neg_t_fu_432_p2, "p_neg_t_fu_432_p2");
    sc_trace(mVcdFile, p_lshr_f_cast_fu_438_p1, "p_lshr_f_cast_fu_438_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, tmp_28_fu_224_p00, "tmp_28_fu_224_p00");
#endif

    }
}

blobsCount::~blobsCount() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

}

void blobsCount::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state2.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                    esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
            ap_enable_reg_pp0_iter3 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter3_reg.read()))) {
        external_1_reg_122 = p_external_1_fu_370_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        external_1_reg_122 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        i_reg_110 = i_cast5_mid2_reg_475.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_reg_110 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        indvar_flatten_reg_99 = indvar_flatten_next_reg_458.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        indvar_flatten_reg_99 = ap_const_lv15_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter3_reg.read()))) {
        internal_1_reg_145 = internal_2_fu_383_p3.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        internal_1_reg_145 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_reg_134 = j_4_reg_494.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_reg_134 = ap_const_lv8_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_fu_183_p2.read()))) {
        exitcond5_reg_463 = exitcond5_fu_195_p2.read();
        j_mid2_reg_469 = j_mid2_fu_201_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        exitcond_flatten_reg_454 = exitcond_flatten_fu_183_p2.read();
        exitcond_flatten_reg_454_pp0_iter1_reg = exitcond_flatten_reg_454.read();
        exitcond_flatten_reg_454_pp0_iter2_reg = exitcond_flatten_reg_454_pp0_iter1_reg.read();
        exitcond_flatten_reg_454_pp0_iter3_reg = exitcond_flatten_reg_454_pp0_iter2_reg.read();
        i_17_reg_448 = i_17_fu_177_p2.read();
        tmp_39_reg_541_pp0_iter3_reg = tmp_39_reg_541.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter2_reg.read()))) {
        external_reg_572 = external_fu_329_p2.read();
        internal_reg_577 = internal_fu_335_p2.read();
        p_px_1_reg_562 = p_px_1_fu_321_p3.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(exitcond5_reg_463.read(), ap_const_lv1_1))) {
        i_17_mid1_reg_481 = i_17_mid1_fu_215_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0))) {
        i_cast5_mid2_cast_reg_499 = i_cast5_mid2_cast_fu_235_p1.read();
        tmp_29_reg_505 = tmp_29_fu_247_p2.read();
        tmp_32_reg_510 = tmp_32_fu_252_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0))) {
        i_cast5_mid2_reg_475 = i_cast5_mid2_fu_209_p3.read();
        j_4_reg_494 = j_4_fu_230_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        indvar_flatten_next_reg_458 = indvar_flatten_next_fu_189_p2.read();
    }
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(exitcond_flatten_reg_454_pp0_iter1_reg.read(), ap_const_lv1_0)) || (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
  esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
  esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
  esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter2_reg.read())))) {
        reg_157 = foreground_clean_q0.read();
        reg_161 = foreground_clean_q1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state11.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_26_reg_597.read()))) {
        tmp_24_reg_607 = p_neg_fu_414_p2.read().range(31, 2);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state10.read())) {
        tmp_25_reg_602 = tmp_fu_390_p2.read().range(31, 2);
        tmp_26_reg_597 = tmp_fu_390_p2.read().range(31, 31);
        tmp_reg_592 = tmp_fu_390_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0))) {
        tmp_28_reg_486 = tmp_28_fu_224_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter2_reg.read()))) {
        tmp_31_reg_551 = grp_fu_165_p2.read();
        tmp_34_reg_557 = grp_fu_171_p2.read();
    }
    if ((esl_seteq<1,1,1>(exitcond_flatten_reg_454_pp0_iter1_reg.read(), ap_const_lv1_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0))) {
        tmp_35_reg_525 = tmp_35_fu_270_p2.read();
        tmp_38_reg_530 = tmp_38_fu_280_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_reg_454_pp0_iter1_reg.read(), ap_const_lv1_0))) {
        tmp_39_reg_541 = tmp_39_fu_289_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, exitcond_flatten_reg_454_pp0_iter2_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_1, tmp_39_reg_541.read()))) {
        tmp_41_reg_567 = grp_fu_171_p2.read();
    }
}

void blobsCount::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[1];
}

void blobsCount::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[2];
}

void blobsCount::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void blobsCount::thread_ap_CS_fsm_state10() {
    ap_CS_fsm_state10 = ap_CS_fsm.read()[3];
}

void blobsCount::thread_ap_CS_fsm_state11() {
    ap_CS_fsm_state11 = ap_CS_fsm.read()[4];
}

void blobsCount::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[5];
}

void blobsCount::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state2_pp0_stage0_iter0() {
    ap_block_state2_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state3_pp0_stage1_iter0() {
    ap_block_state3_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state4_pp0_stage0_iter1() {
    ap_block_state4_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state5_pp0_stage1_iter1() {
    ap_block_state5_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state6_pp0_stage0_iter2() {
    ap_block_state6_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state7_pp0_stage1_iter2() {
    ap_block_state7_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state8_pp0_stage0_iter3() {
    ap_block_state8_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_block_state9_pp0_stage1_iter3() {
    ap_block_state9_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void blobsCount::thread_ap_condition_pp0_exit_iter0_state2() {
    if (esl_seteq<1,1,1>(exitcond_flatten_fu_183_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state2 = ap_const_logic_0;
    }
}

void blobsCount::thread_ap_done() {
    if (((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read()))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void blobsCount::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void blobsCount::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void blobsCount::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void blobsCount::thread_ap_phi_mux_i_phi_fu_114_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_i_phi_fu_114_p4 = i_cast5_mid2_reg_475.read();
    } else {
        ap_phi_mux_i_phi_fu_114_p4 = i_reg_110.read();
    }
}

void blobsCount::thread_ap_phi_mux_indvar_flatten_phi_fu_103_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_indvar_flatten_phi_fu_103_p4 = indvar_flatten_next_reg_458.read();
    } else {
        ap_phi_mux_indvar_flatten_phi_fu_103_p4 = indvar_flatten_reg_99.read();
    }
}

void blobsCount::thread_ap_phi_mux_j_phi_fu_138_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(exitcond_flatten_reg_454.read(), ap_const_lv1_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_phi_fu_138_p4 = j_4_reg_494.read();
    } else {
        ap_phi_mux_j_phi_fu_138_p4 = j_reg_134.read();
    }
}

void blobsCount::thread_ap_ready() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void blobsCount::thread_ap_return() {
    ap_return = (!tmp_26_reg_597.read()[0].is_01())? sc_lv<31>(): ((tmp_26_reg_597.read()[0].to_bool())? p_neg_t_fu_432_p2.read(): p_lshr_f_cast_fu_438_p1.read());
}

void blobsCount::thread_exitcond5_fu_195_p2() {
    exitcond5_fu_195_p2 = (!ap_phi_mux_j_phi_fu_138_p4.read().is_01() || !ap_const_lv8_B3.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_phi_fu_138_p4.read() == ap_const_lv8_B3);
}

void blobsCount::thread_exitcond_flatten_fu_183_p2() {
    exitcond_flatten_fu_183_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_103_p4.read().is_01() || !ap_const_lv15_7DDC.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_indvar_flatten_phi_fu_103_p4.read() == ap_const_lv15_7DDC);
}

void blobsCount::thread_external_fu_329_p2() {
    external_fu_329_p2 = (!external_1_reg_122.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(external_1_reg_122.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void blobsCount::thread_foreground_clean_address0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        foreground_clean_address0 =  (sc_lv<15>) (tmp_36_fu_285_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        foreground_clean_address0 =  (sc_lv<15>) (tmp_30_fu_257_p1.read());
    } else {
        foreground_clean_address0 = "XXXXXXXXXXXXXXX";
    }
}

void blobsCount::thread_foreground_clean_address1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        foreground_clean_address1 =  (sc_lv<15>) (tmp_40_fu_294_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        foreground_clean_address1 =  (sc_lv<15>) (tmp_33_fu_261_p1.read());
    } else {
        foreground_clean_address1 = "XXXXXXXXXXXXXXX";
    }
}

void blobsCount::thread_foreground_clean_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        foreground_clean_ce0 = ap_const_logic_1;
    } else {
        foreground_clean_ce0 = ap_const_logic_0;
    }
}

void blobsCount::thread_foreground_clean_ce1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read())))) {
        foreground_clean_ce1 = ap_const_logic_1;
    } else {
        foreground_clean_ce1 = ap_const_logic_0;
    }
}

void blobsCount::thread_grp_fu_165_p2() {
    grp_fu_165_p2 = (!reg_157.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(reg_157.read() == ap_const_lv8_FF);
}

void blobsCount::thread_grp_fu_171_p2() {
    grp_fu_171_p2 = (!reg_161.read().is_01() || !ap_const_lv8_FF.is_01())? sc_lv<1>(): sc_lv<1>(reg_161.read() == ap_const_lv8_FF);
}

void blobsCount::thread_i_17_cast_mid2_cast_fu_243_p1() {
    i_17_cast_mid2_cast_fu_243_p1 = esl_zext<15,8>(i_17_cast_mid2_fu_238_p3.read());
}

void blobsCount::thread_i_17_cast_mid2_fu_238_p3() {
    i_17_cast_mid2_fu_238_p3 = (!exitcond5_reg_463.read()[0].is_01())? sc_lv<8>(): ((exitcond5_reg_463.read()[0].to_bool())? i_17_mid1_reg_481.read(): i_17_reg_448.read());
}

void blobsCount::thread_i_17_fu_177_p2() {
    i_17_fu_177_p2 = (!ap_phi_mux_i_phi_fu_114_p4.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(ap_phi_mux_i_phi_fu_114_p4.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void blobsCount::thread_i_17_mid1_fu_215_p2() {
    i_17_mid1_fu_215_p2 = (!i_reg_110.read().is_01() || !ap_const_lv8_2.is_01())? sc_lv<8>(): (sc_biguint<8>(i_reg_110.read()) + sc_biguint<8>(ap_const_lv8_2));
}

void blobsCount::thread_i_cast5_mid2_cast_fu_235_p1() {
    i_cast5_mid2_cast_fu_235_p1 = esl_zext<15,8>(i_cast5_mid2_reg_475.read());
}

void blobsCount::thread_i_cast5_mid2_fu_209_p3() {
    i_cast5_mid2_fu_209_p3 = (!exitcond5_reg_463.read()[0].is_01())? sc_lv<8>(): ((exitcond5_reg_463.read()[0].to_bool())? i_17_reg_448.read(): i_reg_110.read());
}

void blobsCount::thread_indvar_flatten_next_fu_189_p2() {
    indvar_flatten_next_fu_189_p2 = (!ap_phi_mux_indvar_flatten_phi_fu_103_p4.read().is_01() || !ap_const_lv15_1.is_01())? sc_lv<15>(): (sc_biguint<15>(ap_phi_mux_indvar_flatten_phi_fu_103_p4.read()) + sc_biguint<15>(ap_const_lv15_1));
}

void blobsCount::thread_internal_2_fu_383_p3() {
    internal_2_fu_383_p3 = (!tmp_43_fu_377_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_43_fu_377_p2.read()[0].to_bool())? internal_reg_577.read(): internal_1_reg_145.read());
}

void blobsCount::thread_internal_fu_335_p2() {
    internal_fu_335_p2 = (!internal_1_reg_145.read().is_01() || !ap_const_lv32_1.is_01())? sc_lv<32>(): (sc_biguint<32>(internal_1_reg_145.read()) + sc_biguint<32>(ap_const_lv32_1));
}

void blobsCount::thread_j_4_fu_230_p2() {
    j_4_fu_230_p2 = (!j_mid2_reg_469.read().is_01() || !ap_const_lv8_1.is_01())? sc_lv<8>(): (sc_biguint<8>(j_mid2_reg_469.read()) + sc_biguint<8>(ap_const_lv8_1));
}

void blobsCount::thread_j_mid2_fu_201_p3() {
    j_mid2_fu_201_p3 = (!exitcond5_fu_195_p2.read()[0].is_01())? sc_lv<8>(): ((exitcond5_fu_195_p2.read()[0].to_bool())? ap_const_lv8_0: ap_phi_mux_j_phi_fu_138_p4.read());
}

void blobsCount::thread_p_cast_fu_298_p1() {
    p_cast_fu_298_p1 = esl_zext<2,1>(tmp_31_reg_551.read());
}

void blobsCount::thread_p_external_1_fu_370_p3() {
    p_external_1_fu_370_p3 = (!tmp_42_fu_364_p2.read()[0].is_01())? sc_lv<32>(): ((tmp_42_fu_364_p2.read()[0].to_bool())? external_reg_572.read(): external_1_reg_122.read());
}

void blobsCount::thread_p_lshr_cast_fu_429_p1() {
    p_lshr_cast_fu_429_p1 = esl_zext<31,30>(tmp_24_reg_607.read());
}

void blobsCount::thread_p_lshr_f_cast_fu_438_p1() {
    p_lshr_f_cast_fu_438_p1 = esl_zext<31,30>(tmp_25_reg_602.read());
}

void blobsCount::thread_p_neg_fu_414_p2() {
    p_neg_fu_414_p2 = (!ap_const_lv32_0.is_01() || !tmp_reg_592.read().is_01())? sc_lv<32>(): (sc_biguint<32>(ap_const_lv32_0) - sc_biguint<32>(tmp_reg_592.read()));
}

void blobsCount::thread_p_neg_t_fu_432_p2() {
    p_neg_t_fu_432_p2 = (!ap_const_lv31_0.is_01() || !p_lshr_cast_fu_429_p1.read().is_01())? sc_lv<31>(): (sc_biguint<31>(ap_const_lv31_0) - sc_biguint<31>(p_lshr_cast_fu_429_p1.read()));
}

void blobsCount::thread_p_px_1_30_fu_350_p3() {
    p_px_1_30_fu_350_p3 = (!tmp_41_reg_567.read()[0].is_01())? sc_lv<3>(): ((tmp_41_reg_567.read()[0].to_bool())? px_4_fu_344_p2.read(): p_px_1_cast_fu_341_p1.read());
}

void blobsCount::thread_p_px_1_cast_fu_341_p1() {
    p_px_1_cast_fu_341_p1 = esl_zext<3,2>(p_px_1_reg_562.read());
}

void blobsCount::thread_p_px_1_fu_321_p3() {
    p_px_1_fu_321_p3 = (!grp_fu_165_p2.read()[0].is_01())? sc_lv<2>(): ((grp_fu_165_p2.read()[0].to_bool())? px_2_fu_315_p2.read(): px_1_fu_308_p3.read());
}

void blobsCount::thread_px_1_fu_308_p3() {
    px_1_fu_308_p3 = (!tmp_34_reg_557.read()[0].is_01())? sc_lv<2>(): ((tmp_34_reg_557.read()[0].to_bool())? px_fu_301_p3.read(): p_cast_fu_298_p1.read());
}

void blobsCount::thread_px_2_fu_315_p2() {
    px_2_fu_315_p2 = (!px_1_fu_308_p3.read().is_01() || !ap_const_lv2_1.is_01())? sc_lv<2>(): (sc_biguint<2>(px_1_fu_308_p3.read()) + sc_biguint<2>(ap_const_lv2_1));
}

void blobsCount::thread_px_3_fu_357_p3() {
    px_3_fu_357_p3 = (!tmp_39_reg_541_pp0_iter3_reg.read()[0].is_01())? sc_lv<3>(): ((tmp_39_reg_541_pp0_iter3_reg.read()[0].to_bool())? p_px_1_30_fu_350_p3.read(): p_px_1_cast_fu_341_p1.read());
}

void blobsCount::thread_px_4_fu_344_p2() {
    px_4_fu_344_p2 = (!p_px_1_cast_fu_341_p1.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<3>(): (sc_biguint<3>(p_px_1_cast_fu_341_p1.read()) + sc_biguint<3>(ap_const_lv3_1));
}

void blobsCount::thread_px_fu_301_p3() {
    px_fu_301_p3 = (!tmp_31_reg_551.read()[0].is_01())? sc_lv<2>(): ((tmp_31_reg_551.read()[0].to_bool())? ap_const_lv2_2: ap_const_lv2_1);
}

void blobsCount::thread_tmp1_fu_265_p2() {
    tmp1_fu_265_p2 = (!tmp_28_reg_486.read().is_01() || !ap_const_lv15_B4.is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_28_reg_486.read()) + sc_biguint<15>(ap_const_lv15_B4));
}

void blobsCount::thread_tmp2_fu_275_p2() {
    tmp2_fu_275_p2 = (!tmp_28_reg_486.read().is_01() || !ap_const_lv15_B5.is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_28_reg_486.read()) + sc_biguint<15>(ap_const_lv15_B5));
}

void blobsCount::thread_tmp_28_fu_224_p0() {
    tmp_28_fu_224_p0 =  (sc_lv<8>) (tmp_28_fu_224_p00.read());
}

void blobsCount::thread_tmp_28_fu_224_p00() {
    tmp_28_fu_224_p00 = esl_zext<15,8>(j_mid2_reg_469.read());
}

void blobsCount::thread_tmp_28_fu_224_p2() {
    tmp_28_fu_224_p2 = (!tmp_28_fu_224_p0.read().is_01() || !ap_const_lv15_B4.is_01())? sc_lv<15>(): sc_biguint<8>(tmp_28_fu_224_p0.read()) * sc_biguint<15>(ap_const_lv15_B4);
}

void blobsCount::thread_tmp_29_fu_247_p2() {
    tmp_29_fu_247_p2 = (!tmp_28_reg_486.read().is_01() || !i_cast5_mid2_cast_fu_235_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_28_reg_486.read()) + sc_biguint<15>(i_cast5_mid2_cast_fu_235_p1.read()));
}

void blobsCount::thread_tmp_30_fu_257_p1() {
    tmp_30_fu_257_p1 = esl_zext<64,15>(tmp_29_reg_505.read());
}

void blobsCount::thread_tmp_32_fu_252_p2() {
    tmp_32_fu_252_p2 = (!tmp_28_reg_486.read().is_01() || !i_17_cast_mid2_cast_fu_243_p1.read().is_01())? sc_lv<15>(): (sc_biguint<15>(tmp_28_reg_486.read()) + sc_biguint<15>(i_17_cast_mid2_cast_fu_243_p1.read()));
}

void blobsCount::thread_tmp_33_fu_261_p1() {
    tmp_33_fu_261_p1 = esl_zext<64,15>(tmp_32_reg_510.read());
}

void blobsCount::thread_tmp_35_fu_270_p2() {
    tmp_35_fu_270_p2 = (!i_cast5_mid2_cast_reg_499.read().is_01() || !tmp1_fu_265_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(i_cast5_mid2_cast_reg_499.read()) + sc_biguint<15>(tmp1_fu_265_p2.read()));
}

void blobsCount::thread_tmp_36_fu_285_p1() {
    tmp_36_fu_285_p1 = esl_zext<64,15>(tmp_35_reg_525.read());
}

void blobsCount::thread_tmp_38_fu_280_p2() {
    tmp_38_fu_280_p2 = (!i_cast5_mid2_cast_reg_499.read().is_01() || !tmp2_fu_275_p2.read().is_01())? sc_lv<15>(): (sc_biguint<15>(i_cast5_mid2_cast_reg_499.read()) + sc_biguint<15>(tmp2_fu_275_p2.read()));
}

void blobsCount::thread_tmp_39_fu_289_p2() {
    tmp_39_fu_289_p2 = (!tmp_38_reg_530.read().is_01() || !ap_const_lv15_7E90.is_01())? sc_lv<1>(): (sc_biguint<15>(tmp_38_reg_530.read()) < sc_biguint<15>(ap_const_lv15_7E90));
}

void blobsCount::thread_tmp_40_fu_294_p1() {
    tmp_40_fu_294_p1 = esl_zext<64,15>(tmp_38_reg_530.read());
}

void blobsCount::thread_tmp_42_fu_364_p2() {
    tmp_42_fu_364_p2 = (!px_3_fu_357_p3.read().is_01() || !ap_const_lv3_1.is_01())? sc_lv<1>(): sc_lv<1>(px_3_fu_357_p3.read() == ap_const_lv3_1);
}

void blobsCount::thread_tmp_43_fu_377_p2() {
    tmp_43_fu_377_p2 = (!px_3_fu_357_p3.read().is_01() || !ap_const_lv3_3.is_01())? sc_lv<1>(): sc_lv<1>(px_3_fu_357_p3.read() == ap_const_lv3_3);
}

void blobsCount::thread_tmp_fu_390_p2() {
    tmp_fu_390_p2 = (!external_1_reg_122.read().is_01() || !internal_1_reg_145.read().is_01())? sc_lv<32>(): (sc_biguint<32>(external_1_reg_122.read()) - sc_biguint<32>(internal_1_reg_145.read()));
}

void blobsCount::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_183_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(exitcond_flatten_fu_183_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 4 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter2.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state10;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state1;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<6>) ("XXXXXX");
            break;
    }
}

}

